Update to internal
Signed-off-by: Ed Tanous <ed.tanous@intel.com>

diff --git a/meta-openbmc-mods/meta-common/recipes-phosphor/preinit-mounts/preinit-mounts/init b/meta-openbmc-mods/meta-common/recipes-phosphor/preinit-mounts/preinit-mounts/init
--- a/meta-openbmc-mods/meta-common/recipes-phosphor/preinit-mounts/preinit-mounts/init
+++ b/meta-openbmc-mods/meta-common/recipes-phosphor/preinit-mounts/preinit-mounts/init
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# Copyright 2017 Intel Corporation
+# Copyright 2017-2019 Intel Corporation
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -21,12 +21,12 @@
 # start with /proc and /tmp mounted
 [ -e /proc/mounts ] || mount -t proc proc /proc
 grep -q /tmp /proc/mounts || mount -t tmpfs -o rw,nosuid,nodev tmp /tmp
+grep -q /sys /proc/mounts || mount -t sysfs -o rw,nosuid,nodev,noexec sys /sys
 
 # list of things that need to be rw at boot
 NV_OVERLAYS="/etc /var /home"
-TMP_FS="/var/log /var/lib/systemd/coredump /media"
 
-# place to mount the real jffs2 backing store
+# place to mount the real ubifs backing store
 RWFS_MNT=/tmp/.rwfs
 
 if grep -q "$RWFS_MNT" /proc/mounts; then
@@ -41,15 +41,15 @@ mtd_by_name() {
     echo "$mtd"
 }
 
-mtdblock_by_name() {
+mtdnum_by_name() {
     local name="$1"
-    local mtdblock="$(mtd_by_name "$name" | sed 's,mtd,mtdblock,')"
-    echo "$mtdblock"
+    local mtdnum="$(grep "$name" /proc/mtd | cut -c 4)"
+    echo "$mtdnum"
 }
 
 NV_MTD=rwfs
 NV_MTD_DEV="$(mtd_by_name ${NV_MTD})"
-NV_MTD_BLOCKDEV="$(mtdblock_by_name ${NV_MTD})"
+NV_MTD_NUM="$(mtdnum_by_name ${NV_MTD})"
 
 nvrw() {
     local p="$1"
@@ -90,14 +90,34 @@ full_clean() {
     done
 }
 
-# check for full factory reset: if so, flash_eraseall $NV_MTD_DEV
-bootflags="0x$(sed 's/^.*bootflags=\([0-9a-f]*\).*$/\1/' /proc/cmdline)"
+# check for full factory reset: if so, ubiformat $NV_MTD_DEV
+bootflags="0x$(sed -n 's/^.*bootflags=\([0-9a-f]*\).*$/\1/p' /proc/cmdline)"
+bootflags=$((bootflags + 0))
 let "restore_op = $bootflags & 0x3"
 if [ $restore_op -eq 3 ]; then
-    flash_eraseall "$NV_MTD_DEV"
+    ubiformat -y "$NV_MTD_DEV"
 fi
 
-mount -t jffs2 "$NV_MTD_BLOCKDEV" "$RWFS_MNT"
+# attach a UBI device to the MTD device
+NV_UBI_DEV="/dev/ubi${NV_MTD_NUM}"
+if [ ! -e $NV_UBI_DEV ]; then
+    if ! ubiattach -m "$NV_MTD_NUM" -d "$NV_MTD_NUM"; then
+        # the attach failed, so format the MTD device and try again
+        echo "Warning! Failed to attach $NV_UBI_DEV to $NV_MTD_DEV."
+        echo "UBI-formatting $NV_MTD_DEV to attach again. Data on this device will be lost."
+        ubiformat -y "$NV_MTD_DEV"
+        ubiattach -m "$NV_MTD_NUM" -d "$NV_MTD_NUM"
+    fi
+fi
+
+# make a UBI volume on the UBI device
+NV_UBI_VOL="${NV_UBI_DEV}_0"
+if [ ! -e $NV_UBI_VOL ]; then
+    ubimkvol "$NV_UBI_DEV" -N "$NV_MTD" -m
+fi
+
+# mount a UBIFS on the UBI volume
+mount -t ubifs "$NV_UBI_VOL" "$RWFS_MNT"
 
 if [ $restore_op -eq 1 ]; then
     targetted_clean
@@ -107,10 +127,6 @@ fi
 
 for FS in $NV_OVERLAYS; do
     nvrw "$FS"
-done
-
-for FS in $TMP_FS; do
-    mount -t tmpfs tmpfs "$FS"
 done
 
 # make sure that /etc/fw_env.config mirrors our current uboot environment
@@ -134,8 +150,31 @@ fi
 if ! grep -q sofs /proc/mounts; then
     mkdir -p /var/sofs
     SOFS_MTD=sofs
-    SOFS_MTD_BLOCKDEV="$(mtdblock_by_name ${SOFS_MTD})"
-    mount -t jffs2 "$SOFS_MTD_BLOCKDEV" /var/sofs
+    SOFS_MTD_DEV="$(mtd_by_name ${SOFS_MTD})"
+    SOFS_MTD_NUM="$(mtdnum_by_name ${SOFS_MTD})"
+    SOFS_UBI_DEV="/dev/ubi${SOFS_MTD_NUM}"
+
+    # attach a UBI device to the MTD device
+    if [ ! -e $SOFS_UBI_DEV ]; then
+        if ! ubiattach -m "$SOFS_MTD_NUM" -d "$SOFS_MTD_NUM"; then
+            # the attach failed, so format the MTD device and try again
+            echo "Warning! Failed to attach $SOFS_UBI_DEV to $SOFS_MTD_DEV."
+            echo "UBI-formatting $SOFS_MTD_DEV to attach again. Data on this device will be lost."
+            ubiformat -y "$SOFS_MTD_DEV"
+            ubiattach -m "$SOFS_MTD_NUM" -d "$SOFS_MTD_NUM"
+        fi
+    fi
+
+    # make a UBI volume on the UBI device
+    SOFS_UBI_VOL="${SOFS_UBI_DEV}_0"
+    if [ ! -e $SOFS_UBI_VOL ]; then
+        ubimkvol "$SOFS_UBI_DEV" -N "$SOFS_MTD" -m
+    fi
+
+    # mount a UBIFS on the UBI volume
+    mount -t ubifs "$SOFS_UBI_VOL" /var/sofs
 fi
 
 echo "Finished mounting non-volatile overlays"
+
+exec /lib/systemd/systemd
